import { OrbitSystemConfig } from '@/types/orbit';

export const DEFAULT_ORBIT_CONFIG: OrbitSystemConfig = {
  centerClearRadius: 240,
  backgroundRadius: 900,
  enableAnimation: true,
  mobileMaxOrbits: 2,

  techOrder: ['python', 'java', 'html', 'github', 'vercel', 'railway', 'nextjs'],

  orbits: [
    {
      radius: 320,
      speed: 0.015,
      direction: 1,
      strokeWidth: 1.5,
      strokeOpacity: 0.35,
      dashArray: '4 4',
      elementCount: 8,
      iconSize: 32,
      primaryColor: '#3B82F6',
      secondaryColor: '#93C5FD',
      fillOpacity: 0.95,
      depthOffset: 0,
    },
    {
      radius: 420,
      speed: 0.012,
      direction: -1,
      strokeWidth: 1.2,
      strokeOpacity: 0.28,
      dashArray: '6 6',
      elementCount: 12,
      iconSize: 36,
      primaryColor: '#10B981',
      secondaryColor: '#6EE7B7',
      fillOpacity: 0.75,
      depthOffset: 12,
    },
    {
      radius: 540,
      speed: 0.008,
      direction: 1,
      strokeWidth: 1,
      strokeOpacity: 0.22,
      dashArray: '4 10',
      elementCount: 16,
      iconSize: 40,
      primaryColor: '#8B5CF6',
      secondaryColor: '#C4B5FD',
      fillOpacity: 0.55,
      depthOffset: 24,
      hideOnMobile: true,
    },
    {
      radius: 680,
      speed: 0.006,
      direction: -1,
      strokeWidth: 1,
      strokeOpacity: 0.18,
      dashArray: '2 12',
      elementCount: 20,
      iconSize: 44,
      primaryColor: '#F59E0B',
      secondaryColor: '#FCD34D',
      fillOpacity: 0.35,
      depthOffset: 36,
      hideOnMobile: true,
    },
  ],
};
