import { OrbitSystemConfig } from '@/types/orbit';

export const DEFAULT_ORBIT_CONFIG: OrbitSystemConfig = {
  centerClearRadius: 240,
  backgroundRadius: 0,
  enableAnimation: true,
  mobileMaxOrbits: 2,

  techOrder: ['python', 'java', 'html', 'github', 'vercel', 'railway', 'nextjs'],

  orbits: [
    {
      radius: 420,
      speed: 0.015,
      direction: 1,
      strokeWidth: 1.5,
      strokeOpacity: 0.4,
      dashArray: '4 4',
      elementCount: 8,
      iconSize: 36,
      primaryColor: '#3B82F6',
      secondaryColor: '#93C5FD',
      fillOpacity: 0.95,
      depthOffset: 0,

      // new visual properties
      iconOpacity: 1,
      fillColor: '#FFFFFF',
      rimColor: '#E5E7EB',
      shadowColor: '#000000',
      lift: 0,
      shadowBlur: 20,
      shadowOffset: 14,
    },
    {
      radius: 520,
      speed: 0.012,
      direction: -1,
      strokeWidth: 1.2,
      strokeOpacity: 0.35,
      dashArray: '6 6',
      elementCount: 12,
      iconSize: 40,
      primaryColor: '#10B981',
      secondaryColor: '#6EE7B7',
      fillOpacity: 0.75,
      depthOffset: 12,

      // new visual properties
      iconOpacity: 0.9,
      fillColor: '#F9FAFB',
      rimColor: '#D1D5DB',
      shadowColor: '#000000',
      lift: 18,
      shadowBlur: 26,
      shadowOffset: 22,
    },
    {
      radius: 640,
      speed: 0.008,
      direction: 1,
      strokeWidth: 1,
      strokeOpacity: 0.22,
      dashArray: '4 10',
      elementCount: 16,
      iconSize: 44,
      primaryColor: '#8B5CF6',
      secondaryColor: '#C4B5FD',
      fillOpacity: 0.55,
      depthOffset: 24,
      hideOnMobile: true,

      // new visual properties
      iconOpacity: 0.8,
      fillColor: '#F3F4F6',
      rimColor: '#E5E7EB',
      shadowColor: '#000000',
      lift: 24,
      shadowBlur: 32,
      shadowOffset: 28,
    },
    {
      radius: 780,
      speed: 0.006,
      direction: -1,
      strokeWidth: 1,
      strokeOpacity: 0.18,
      dashArray: '2 12',
      elementCount: 20,
      iconSize: 48,
      primaryColor: '#F59E0B',
      secondaryColor: '#FCD34D',
      fillOpacity: 0.35,
      depthOffset: 36,
      hideOnMobile: true,

      // new visual properties
      iconOpacity: 0.7,
      fillColor: '#FFFAF0',
      rimColor: '#FDE68A',
      shadowColor: '#000000',
      lift: 36,
      shadowBlur: 40,
      shadowOffset: 34,
    },
    {
      radius: 880,
      speed: 0.009,
      direction: 1,
      strokeWidth: 1,
      strokeOpacity: 0.18,
      dashArray: '4 10',
      elementCount: 20,
      iconSize: 52,
      primaryColor: '#F59E0B',
      secondaryColor: '#FCD34D',
      fillOpacity: 0.05,
      depthOffset: 48,
      hideOnMobile: true,

      // new visual properties
      iconOpacity: 0.6,
      fillColor: '#FFFAF0',
      rimColor: '#FDE68A',
      shadowColor: '#000000',
      lift: 48,
      shadowBlur: 48,
      shadowOffset: 40,
    },
    {
      radius: 1080,
      speed: 0.007,
      direction: -1,
      strokeWidth: 1,
      strokeOpacity: 0.18,
      dashArray: '2 12',
      elementCount: 28,
      iconSize: 56,
      primaryColor: '#F59E0B',
      secondaryColor: '#FCD34D',
      fillOpacity: 0.04,
      depthOffset: 48,
      hideOnMobile: true,

      // new visual properties
      iconOpacity: 0.5,
      fillColor: '#FFFAF0',
      rimColor: '#FDE68A',
      shadowColor: '#000000',
      lift: 48,
      shadowBlur: 48,
      shadowOffset: 40,
    },
  ],
};
